version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    #volumes:
      #- /home/incardona/Scrivania/jupyter-docker/workspace:ro
    volumes:
      - /Users/asso210/Desktop/Desktop/borsa_micciche_mantegna/dashboard/data:/data/networks:ro
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - backend

